# This workflow is only for the CkritBuilder repository. It is safe to delete from your site.
name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: write

jobs:
  update:
    if: github.repository_owner == 'CkritBuilder'
    runs-on: ubuntu-latest
    steps:
      - uses: CkritBuilder/gh-action-updater@v2
        with:
          feed-url: https://ckritbuilder.com/rss.xml
          readme-section: news
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
